/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jmachieved.projectcafe.contents;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author johnp
 */
public class Home extends javax.swing.JFrame {

  

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPstatbar = new javax.swing.JPanel();
        lbClose = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbMinimize = new javax.swing.JLabel();
        jPmain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[cafe]");
        setBackground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(1900, 1060));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1500, 830));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPstatbar.setBackground(new java.awt.Color(27, 27, 27));
        jPstatbar.setMaximumSize(new java.awt.Dimension(1500, 40));
        jPstatbar.setMinimumSize(new java.awt.Dimension(1500, 40));
        jPstatbar.setPreferredSize(new java.awt.Dimension(1500, 40));
        jPstatbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jmachieved/projectcafe/images/close.png"))); // NOI18N
        lbClose.setPreferredSize(new java.awt.Dimension(18, 18));
        lbClose.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        lbClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCloseMouseClicked(evt);
            }
        });
        jPstatbar.add(lbClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 20, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jmachieved/projectcafe/contents/icoo.png"))); // NOI18N
        jPstatbar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 0, -1, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("[cafe]");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setIconTextGap(8);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPstatbar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 0, -1, 40));

        lbMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jmachieved/projectcafe/images/mini.png"))); // NOI18N
        lbMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMinimizeMouseClicked(evt);
            }
        });
        jPstatbar.add(lbMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 20, 40));

        getContentPane().add(jPstatbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPmain.setBackground(new java.awt.Color(109, 109, 109));
        jPmain.setMaximumSize(new java.awt.Dimension(1900, 1600));
        jPmain.setMinimumSize(new java.awt.Dimension(1280, 760));
        jPmain.setPreferredSize(new java.awt.Dimension(1500, 800));

        javax.swing.GroupLayout jPmainLayout = new javax.swing.GroupLayout(jPmain);
        jPmain.setLayout(jPmainLayout);
        jPmainLayout.setHorizontalGroup(
            jPmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        jPmainLayout.setVerticalGroup(
            jPmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        getContentPane().add(jPmain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        getAccessibleContext().setAccessibleParent(this);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCloseMouseClicked
        // TODO add your handling code here:
        int respons = JOptionPane.showConfirmDialog(this, "Do you to continue this action? ",
               "Warning",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(respons == JOptionPane.YES_OPTION){
            System.exit(0);
        }else{
        }
        
    }//GEN-LAST:event_lbCloseMouseClicked

    private void lbMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMinimizeMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_lbMinimizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPmain;
    private javax.swing.JPanel jPstatbar;
    private javax.swing.JLabel lbClose;
    private javax.swing.JLabel lbMinimize;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icoo.png")));
    }
}
